from rest_framework import viewsets, views, status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.exceptions import PermissionDenied
from django.db.models import Sum
from datetime import datetime, date, timedelta
from .models import Employee, ScanEntry, SalaryRecord
from .serializers import EmployeeSerializer, ScanEntrySerializer, SalaryRecordSerializer
from .permissions import IsAdminRole
import calendar
import math
from django.http import JsonResponse

def root_view(request):
    return JsonResponse({
        "message": "Scanner Project Backend is running!",
        "api_root": "/api/",
        "admin": "/admin/"
    })

def get_working_days(year, month):
    num_days = calendar.monthrange(year, month)[1]
    working_days = 0
    for day in range(1, num_days + 1):
        if date(year, month, day).weekday() != 6: # Sunday is 6
            working_days += 1
    return working_days

def get_employee_for_user(user):
    employee = Employee.objects.filter(user=user).first()
    if not employee:
        employee = Employee.objects.filter(name__iexact=user.username).first()
    return employee

def is_admin_user(user, employee=None):
    if user.is_superuser:
        return True
    if not employee:
        employee = get_employee_for_user(user)
    return bool(employee and employee.role == 'Admin')

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def dashboard_stats(request):
    from django.conf import settings
    today = date.today()
    year = today.year
    month = today.month

    working_days = get_working_days(year, month)
    total_target_scans = working_days * 2250

    employee = get_employee_for_user(request.user)
    is_admin = is_admin_user(request.user, employee)

    all_month_scans = ScanEntry.objects.filter(date__month=month, date__year=year)
    user_month_scans = all_month_scans.filter(user=request.user)
    
    # Collective total is always the sum of ALL scans in the month
    collective_scans = all_month_scans.aggregate(Sum('scan_count'))['scan_count__sum'] or 0
    
    # Individual total is only for the current user
    individual_scans = user_month_scans.aggregate(Sum('scan_count'))['scan_count__sum'] or 0

    # Formulas for salary estimates
    # A team contains 2 people.
    team_member_count = 2
    # Team Wage: Total money generated by the group
    shared_salary = ((collective_scans / 2250) * 800)
    # Person Wage: Individual person's money (50% split of the group's earnings)
    personal_salary = shared_salary / team_member_count

    remaining_scans = max(0, total_target_scans - collective_scans)
    
    # Calculate remaining working days (excluding Sundays)
    remaining_working_days = sum(
        1
        for day in range(today.day, calendar.monthrange(year, month)[1] + 1)
        if date(year, month, day).weekday() != 6
    )
    
    required_scans_per_day = math.ceil(remaining_scans / remaining_working_days) if remaining_working_days else 0
    progress_percentage = min(100, (collective_scans / total_target_scans * 100) if total_target_scans > 0 else 0)

    # Calculate per-person breakdown for admins
    employee_breakdown = []
    if is_admin:
        # Build the breakdown from the full month dataset so team totals stay separate from personal totals.
        for emp in Employee.objects.all():
            emp_scans = all_month_scans.filter(employee=emp).aggregate(Sum('scan_count'))['scan_count__sum'] or 0
            emp_salary = ((emp_scans / 2250) * 800)
            employee_breakdown.append({
                "name": emp.name,
                "scans": emp_scans,
                "salary": round(emp_salary, 2)
            })

    google_sheets_config = {
        "is_configured": bool(getattr(settings, 'GOOGLE_SERVICE_ACCOUNT_JSON', None) and getattr(settings, 'GOOGLE_SHEETS_SPREADSHEET_ID', None)),
        "spreadsheet_id": getattr(settings, 'GOOGLE_SHEETS_SPREADSHEET_ID', ''),
        "sheet_url": f"https://docs.google.com/spreadsheets/d/{getattr(settings, 'GOOGLE_SHEETS_SPREADSHEET_ID', '')}/edit" if getattr(settings, 'GOOGLE_SHEETS_SPREADSHEET_ID', None) else ""
    }

    return Response({
        "authenticated_username": request.user.username,
        "is_admin": is_admin,
        "current_month": today.strftime("%B %Y"),
        "working_days": working_days,
        "collective_scans": collective_scans,
        "individual_scans": individual_scans,
        "shared_salary_estimate": round(shared_salary, 2),
        "personal_salary_estimate": round(personal_salary, 2),
        "remaining_scans": remaining_scans,
        "required_scans_per_day": required_scans_per_day,
        "progress_percentage": round(progress_percentage, 1),
        "target_scans": total_target_scans,
        "employee_breakdown": employee_breakdown,
        "google_sheets_sync": google_sheets_config
    }, headers={'Cache-Control': 'no-store'})

@api_view(['POST'])
@permission_classes([IsAuthenticated, IsAdminRole])
def force_sheets_sync(request):
    from .google_sheets import sync_data_to_sheets
    success, message = sync_data_to_sheets()
    if success:
        return Response({"status": "success", "message": message}, status=status.HTTP_200_OK)
    return Response({"status": "error", "message": message}, status=status.HTTP_400_BAD_REQUEST)


class EmployeeViewSet(viewsets.ModelViewSet):
    serializer_class = EmployeeSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        employee = get_employee_for_user(user)
        if is_admin_user(user, employee):
            return Employee.objects.all()
        return Employee.objects.filter(id=employee.id) if employee else Employee.objects.none()

    def perform_create(self, serializer):
        if not is_admin_user(self.request.user):
            raise PermissionDenied("Only admins can create employees.")
        serializer.save()

    def perform_update(self, serializer):
        if not is_admin_user(self.request.user):
            raise PermissionDenied("Only admins can edit employees.")
        serializer.save()

    def perform_destroy(self, instance):
        if not is_admin_user(self.request.user):
            raise PermissionDenied("Only admins can delete employees.")
        instance.delete()

class ScanEntryViewSet(viewsets.ModelViewSet):
    serializer_class = ScanEntrySerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        employee = get_employee_for_user(user)
        if is_admin_user(user, employee):
            return ScanEntry.objects.all().order_by('-date')
        return ScanEntry.objects.filter(user=user).order_by('-date')

    def perform_create(self, serializer):
        employee = get_employee_for_user(self.request.user)
        # Automatically assign the logged-in user as owner
        serializer.save(user=self.request.user, employee=employee)

class SalaryRecordViewSet(viewsets.ModelViewSet):
    queryset = SalaryRecord.objects.all().order_by('-month')
    serializer_class = SalaryRecordSerializer
    permission_classes = [IsAuthenticated, IsAdminRole]
